# Generated by Django 4.2.30 on 2026-08-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='confirmed_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='confirmed_by_manager_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
