# Generated by Django 4.2.30 on 2026-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workshop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
