# Generated by Django 4.2.30 on 2026-07-25 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_workshop_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_legal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reception', 'پذیرش'), ('technical', 'فنی'), ('accounting', 'حسابداری'), ('management', 'مدیریت'), ('payment', 'پرداخت'), ('done', 'تکمیل')], default='reception', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField()),
                ('code', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='کد سفارش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار/زمان')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ نهایی')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام خدمت/عملیات')),
                ('machine_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام دستگاه (اختیاری)')),
                ('unit', models.CharField(choices=[('day', 'روز'), ('hour', 'ساعت'), ('minute', 'دقیقه'), ('seconds', 'ثانیه'), ('ton', 'تن'), ('kg', 'کیلوگرم'), ('gram', 'گرم'), ('count', 'عدد'), ('meter', 'متر'), ('cmeter', 'سانتی متر'), ('mmeter', 'میلی متر'), ('sqmeter', 'مترمربع'), ('adl', 'عدل'), ('mesghal', 'مثقال'), ('jin', 'جین')], max_length=20, verbose_name='واحد اندازه\u200cگیری')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پایه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/attachments/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/activities/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.orderactivity')),
            ],
        ),
        migrations.AddField(
            model_name='orderactivity',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.servicetype', verbose_name='نوع عملیات'),
        ),
        migrations.CreateModel(
            name='OrderCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'jalali_year')},
            },
        ),
    ]
