# Generated by Django 4.2.30 on 2026-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_workshop',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='machine_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
