# Generated by Django 4.2.30 on 2026-07-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_customer_workshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_workshop',
            new_name='customer_workshop_name',
        ),
    ]
