# Generated by Django 4.2.30 on 2026-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_archived_order_is_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_request',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
