# Generated by Django 6.1 on 2026-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_count_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('reception', 'پذیرش'), ('technical', 'فنی'), ('accounting', 'حسابداری'), ('management', 'مدیریت'), ('payment', 'پرداخت'), ('done', 'تکمیل'), ('release', 'ترخیص')], default='reception', max_length=20),
        ),
    ]
