# Generated by Django 4.2.30 on 2026-08-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_release_allowed',
            field=models.BooleanField(default=False, verbose_name='مجوز ترخیص مدیر'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_release_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد مجاز ترخیص مدیر'),
        ),
        migrations.CreateModel(
            name='OrderRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=20, unique=True, verbose_name='شماره برگه ترخیص')),
                ('count', models.PositiveSmallIntegerField(verbose_name='تعداد ترخیص')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('is_manager_ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='orders.order')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
